<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TTL_Failed</name>
   <tag></tag>
   <elementGuidId>602344cd-0765-42ec-943e-6af445e4a54e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;container&quot;]/div/div/div[1]/div[2]/div/div[2]/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Text</name>
      <type>Main</type>
      <value>Sorry, something went wrong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;container&quot;]/div/div/div[1]/div[2]/div/div[2]/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
